### ISSUE TITLE
list variable error

### ISSUE THREAD

**Issue by aavileli** [leucos/ansible-proxysql#1]
proxysql.cnf.j2 : -

mysql_query_rules:
(
{% for usr in proxysql_mysql_users %}
  {
    rule_id={{ loop.index }}
    match_pattern="{{ rule.match_pattern }}",
    destination_hostgroup={{ rule.destination_hostgroup | default(0) }}
  }
{%   if not loop.last %},

{%   endif %}
{% endfor %}
)

This should be :- 

mysql_query_rules:
(
{% for rule in proxysql_mysql_query_rules %}
  {
    rule_id={{ loop.index }}
    match_pattern="{{ rule.match_pattern }}",
    destination_hostgroup={{ rule.destination_hostgroup | default(0) }}
  }
{%   if not loop.last %},

{%   endif %}
{% endfor %}
)

**Comment by leucos** [comment]
Fixed, thanks @aavileli !
